/*
 * This file is generated by jOOQ.
 */
package com.heerkirov.animation.jooq.tables.records;


import com.heerkirov.animation.jooq.tables.Animation;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnimationRecord extends UpdatableRecordImpl<AnimationRecord> {

    private static final long serialVersionUID = -1302603188;

    /**
     * Setter for <code>public.animation.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.animation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.animation.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.animation.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.animation.origin_title</code>.
     */
    public void setOriginTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.animation.origin_title</code>.
     */
    public String getOriginTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.animation.other_title</code>.
     */
    public void setOtherTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.animation.other_title</code>.
     */
    public String getOtherTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.animation.cover</code>.
     */
    public void setCover(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.animation.cover</code>.
     */
    public String getCover() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.animation.original_work_type</code>.
     */
    public void setOriginalWorkType(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.animation.original_work_type</code>.
     */
    public Short getOriginalWorkType() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.animation.publish_type</code>.
     */
    public void setPublishType(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.animation.publish_type</code>.
     */
    public Short getPublishType() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.animation.publish_time</code>.
     */
    public void setPublishTime(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.animation.publish_time</code>.
     */
    public LocalDate getPublishTime() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>public.animation.duration</code>.
     */
    public void setDuration(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.animation.duration</code>.
     */
    public Integer getDuration() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.animation.sum_quantity</code>.
     */
    public void setSumQuantity(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.animation.sum_quantity</code>.
     */
    public Integer getSumQuantity() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.animation.published_quantity</code>.
     */
    public void setPublishedQuantity(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.animation.published_quantity</code>.
     */
    public Integer getPublishedQuantity() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.animation.published_record</code>.
     */
    public void setPublishedRecord(LocalDateTime[] value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.animation.published_record</code>.
     */
    public LocalDateTime[] getPublishedRecord() {
        return (LocalDateTime[]) get(11);
    }

    /**
     * Setter for <code>public.animation.publish_plan</code>.
     */
    public void setPublishPlan(LocalDateTime[] value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.animation.publish_plan</code>.
     */
    public LocalDateTime[] getPublishPlan() {
        return (LocalDateTime[]) get(12);
    }

    /**
     * Setter for <code>public.animation.introduction</code>.
     */
    public void setIntroduction(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.animation.introduction</code>.
     */
    public String getIntroduction() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.animation.keyword</code>.
     */
    public void setKeyword(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.animation.keyword</code>.
     */
    public String getKeyword() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.animation.limit_level_sex</code>.
     */
    public void setLimitLevelSex(Short value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.animation.limit_level_sex</code>.
     */
    public Short getLimitLevelSex() {
        return (Short) get(15);
    }

    /**
     * Setter for <code>public.animation.limit_level_violence</code>.
     */
    public void setLimitLevelViolence(Short value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.animation.limit_level_violence</code>.
     */
    public Short getLimitLevelViolence() {
        return (Short) get(16);
    }

    /**
     * Setter for <code>public.animation.relations</code>.
     */
    public void setRelations(JSONB value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.animation.relations</code>.
     */
    public JSONB getRelations() {
        return (JSONB) get(17);
    }

    /**
     * Setter for <code>public.animation.relations_topology</code>.
     */
    public void setRelationsTopology(JSONB value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.animation.relations_topology</code>.
     */
    public JSONB getRelationsTopology() {
        return (JSONB) get(18);
    }

    /**
     * Setter for <code>public.animation.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.animation.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>public.animation.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.animation.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for <code>public.animation.creator</code>.
     */
    public void setCreator(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.animation.creator</code>.
     */
    public Integer getCreator() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>public.animation.updater</code>.
     */
    public void setUpdater(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.animation.updater</code>.
     */
    public Integer getUpdater() {
        return (Integer) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnimationRecord
     */
    public AnimationRecord() {
        super(Animation.ANIMATION);
    }

    /**
     * Create a detached, initialised AnimationRecord
     */
    public AnimationRecord(Integer id, String title, String originTitle, String otherTitle, String cover, Short originalWorkType, Short publishType, LocalDate publishTime, Integer duration, Integer sumQuantity, Integer publishedQuantity, LocalDateTime[] publishedRecord, LocalDateTime[] publishPlan, String introduction, String keyword, Short limitLevelSex, Short limitLevelViolence, JSONB relations, JSONB relationsTopology, LocalDateTime createTime, LocalDateTime updateTime, Integer creator, Integer updater) {
        super(Animation.ANIMATION);

        set(0, id);
        set(1, title);
        set(2, originTitle);
        set(3, otherTitle);
        set(4, cover);
        set(5, originalWorkType);
        set(6, publishType);
        set(7, publishTime);
        set(8, duration);
        set(9, sumQuantity);
        set(10, publishedQuantity);
        set(11, publishedRecord);
        set(12, publishPlan);
        set(13, introduction);
        set(14, keyword);
        set(15, limitLevelSex);
        set(16, limitLevelViolence);
        set(17, relations);
        set(18, relationsTopology);
        set(19, createTime);
        set(20, updateTime);
        set(21, creator);
        set(22, updater);
    }
}
