/*
 * This file is generated by jOOQ.
 */
package com.heerkirov.animation.jooq.tables.records;


import com.heerkirov.animation.jooq.tables.AnimationTagRelation;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnimationTagRelationRecord extends UpdatableRecordImpl<AnimationTagRelationRecord> implements Record3<Long, Integer, Integer> {

    private static final long serialVersionUID = -1384159627;

    /**
     * Setter for <code>public.animation_tag_relation.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.animation_tag_relation.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.animation_tag_relation.animation_id</code>.
     */
    public void setAnimationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.animation_tag_relation.animation_id</code>.
     */
    public Integer getAnimationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.animation_tag_relation.tag_id</code>.
     */
    public void setTagId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.animation_tag_relation.tag_id</code>.
     */
    public Integer getTagId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AnimationTagRelation.ANIMATION_TAG_RELATION.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AnimationTagRelation.ANIMATION_TAG_RELATION.ANIMATION_ID;
    }

    @Override
    public Field<Integer> field3() {
        return AnimationTagRelation.ANIMATION_TAG_RELATION.TAG_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAnimationId();
    }

    @Override
    public Integer component3() {
        return getTagId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAnimationId();
    }

    @Override
    public Integer value3() {
        return getTagId();
    }

    @Override
    public AnimationTagRelationRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AnimationTagRelationRecord value2(Integer value) {
        setAnimationId(value);
        return this;
    }

    @Override
    public AnimationTagRelationRecord value3(Integer value) {
        setTagId(value);
        return this;
    }

    @Override
    public AnimationTagRelationRecord values(Long value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnimationTagRelationRecord
     */
    public AnimationTagRelationRecord() {
        super(AnimationTagRelation.ANIMATION_TAG_RELATION);
    }

    /**
     * Create a detached, initialised AnimationTagRelationRecord
     */
    public AnimationTagRelationRecord(Long id, Integer animationId, Integer tagId) {
        super(AnimationTagRelation.ANIMATION_TAG_RELATION);

        set(0, id);
        set(1, animationId);
        set(2, tagId);
    }
}
