/*
 * This file is generated by jOOQ.
 */
package com.heerkirov.animation.jooq.tables.records;


import com.heerkirov.animation.jooq.tables.AnimationStaffRelation;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnimationStaffRelationRecord extends UpdatableRecordImpl<AnimationStaffRelationRecord> implements Record4<Long, Integer, Integer, Short> {

    private static final long serialVersionUID = -1445812311;

    /**
     * Setter for <code>public.animation_staff_relation.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.animation_staff_relation.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.animation_staff_relation.animation_id</code>.
     */
    public void setAnimationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.animation_staff_relation.animation_id</code>.
     */
    public Integer getAnimationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.animation_staff_relation.staff_id</code>.
     */
    public void setStaffId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.animation_staff_relation.staff_id</code>.
     */
    public Integer getStaffId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.animation_staff_relation.staff_type</code>.
     */
    public void setStaffType(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.animation_staff_relation.staff_type</code>.
     */
    public Short getStaffType() {
        return (Short) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Integer, Integer, Short> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Integer, Integer, Short> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AnimationStaffRelation.ANIMATION_STAFF_RELATION.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AnimationStaffRelation.ANIMATION_STAFF_RELATION.ANIMATION_ID;
    }

    @Override
    public Field<Integer> field3() {
        return AnimationStaffRelation.ANIMATION_STAFF_RELATION.STAFF_ID;
    }

    @Override
    public Field<Short> field4() {
        return AnimationStaffRelation.ANIMATION_STAFF_RELATION.STAFF_TYPE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAnimationId();
    }

    @Override
    public Integer component3() {
        return getStaffId();
    }

    @Override
    public Short component4() {
        return getStaffType();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAnimationId();
    }

    @Override
    public Integer value3() {
        return getStaffId();
    }

    @Override
    public Short value4() {
        return getStaffType();
    }

    @Override
    public AnimationStaffRelationRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AnimationStaffRelationRecord value2(Integer value) {
        setAnimationId(value);
        return this;
    }

    @Override
    public AnimationStaffRelationRecord value3(Integer value) {
        setStaffId(value);
        return this;
    }

    @Override
    public AnimationStaffRelationRecord value4(Short value) {
        setStaffType(value);
        return this;
    }

    @Override
    public AnimationStaffRelationRecord values(Long value1, Integer value2, Integer value3, Short value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnimationStaffRelationRecord
     */
    public AnimationStaffRelationRecord() {
        super(AnimationStaffRelation.ANIMATION_STAFF_RELATION);
    }

    /**
     * Create a detached, initialised AnimationStaffRelationRecord
     */
    public AnimationStaffRelationRecord(Long id, Integer animationId, Integer staffId, Short staffType) {
        super(AnimationStaffRelation.ANIMATION_STAFF_RELATION);

        set(0, id);
        set(1, animationId);
        set(2, staffId);
        set(3, staffType);
    }
}
