/*
 * This file is generated by jOOQ.
 */
package com.heerkirov.animation.jooq.tables.records;


import com.heerkirov.animation.jooq.tables.Tag;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagRecord extends UpdatableRecordImpl<TagRecord> implements Record7<Integer, String, String, LocalDateTime, LocalDateTime, Integer, Integer> {

    private static final long serialVersionUID = -309707440;

    /**
     * Setter for <code>public.tag.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tag.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tag.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tag.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tag.introduction</code>.
     */
    public void setIntroduction(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tag.introduction</code>.
     */
    public String getIntroduction() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tag.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tag.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.tag.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tag.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.tag.creator</code>.
     */
    public void setCreator(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tag.creator</code>.
     */
    public Integer getCreator() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.tag.updater</code>.
     */
    public void setUpdater(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tag.updater</code>.
     */
    public Integer getUpdater() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, LocalDateTime, LocalDateTime, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, LocalDateTime, LocalDateTime, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Tag.TAG.ID;
    }

    @Override
    public Field<String> field2() {
        return Tag.TAG.NAME;
    }

    @Override
    public Field<String> field3() {
        return Tag.TAG.INTRODUCTION;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Tag.TAG.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Tag.TAG.UPDATE_TIME;
    }

    @Override
    public Field<Integer> field6() {
        return Tag.TAG.CREATOR;
    }

    @Override
    public Field<Integer> field7() {
        return Tag.TAG.UPDATER;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getIntroduction();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdateTime();
    }

    @Override
    public Integer component6() {
        return getCreator();
    }

    @Override
    public Integer component7() {
        return getUpdater();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getIntroduction();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdateTime();
    }

    @Override
    public Integer value6() {
        return getCreator();
    }

    @Override
    public Integer value7() {
        return getUpdater();
    }

    @Override
    public TagRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TagRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TagRecord value3(String value) {
        setIntroduction(value);
        return this;
    }

    @Override
    public TagRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public TagRecord value5(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public TagRecord value6(Integer value) {
        setCreator(value);
        return this;
    }

    @Override
    public TagRecord value7(Integer value) {
        setUpdater(value);
        return this;
    }

    @Override
    public TagRecord values(Integer value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagRecord
     */
    public TagRecord() {
        super(Tag.TAG);
    }

    /**
     * Create a detached, initialised TagRecord
     */
    public TagRecord(Integer id, String name, String introduction, LocalDateTime createTime, LocalDateTime updateTime, Integer creator, Integer updater) {
        super(Tag.TAG);

        set(0, id);
        set(1, name);
        set(2, introduction);
        set(3, createTime);
        set(4, updateTime);
        set(5, creator);
        set(6, updater);
    }
}
