/*
 * This file is generated by jOOQ.
 */
package com.heerkirov.animation.jooq.tables.records;


import com.heerkirov.animation.jooq.tables.User;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record4<Integer, String, Boolean, JSONB> {

    private static final long serialVersionUID = -891260074;

    /**
     * Setter for <code>public.user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.user.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user.is_staff</code>.
     */
    public void setIsStaff(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user.is_staff</code>.
     */
    public Boolean getIsStaff() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.user.setting</code>.
     */
    public void setSetting(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user.setting</code>.
     */
    public JSONB getSetting() {
        return (JSONB) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Boolean, JSONB> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Boolean, JSONB> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.USERNAME;
    }

    @Override
    public Field<Boolean> field3() {
        return User.USER.IS_STAFF;
    }

    @Override
    public Field<JSONB> field4() {
        return User.USER.SETTING;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public Boolean component3() {
        return getIsStaff();
    }

    @Override
    public JSONB component4() {
        return getSetting();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public Boolean value3() {
        return getIsStaff();
    }

    @Override
    public JSONB value4() {
        return getSetting();
    }

    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserRecord value3(Boolean value) {
        setIsStaff(value);
        return this;
    }

    @Override
    public UserRecord value4(JSONB value) {
        setSetting(value);
        return this;
    }

    @Override
    public UserRecord values(Integer value1, String value2, Boolean value3, JSONB value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String username, Boolean isStaff, JSONB setting) {
        super(User.USER);

        set(0, id);
        set(1, username);
        set(2, isStaff);
        set(3, setting);
    }
}
