/*
 * This file is generated by jOOQ.
 */
package com.heerkirov.animation.jooq;


import com.heerkirov.animation.jooq.tables.AnimationStaffRelation;
import com.heerkirov.animation.jooq.tables.AnimationTagRelation;
import com.heerkirov.animation.jooq.tables.Comment;
import com.heerkirov.animation.jooq.tables.Diary;
import com.heerkirov.animation.jooq.tables.Message;
import com.heerkirov.animation.jooq.tables.Statistics;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ANIMATION_STAFF_RELATION__INDEX = Indexes0.ANIMATION_STAFF_RELATION__INDEX;
    public static final Index ANIMATION_TAG_RELATION__INDEX = Indexes0.ANIMATION_TAG_RELATION__INDEX;
    public static final Index COMMENT__INDEX = Indexes0.COMMENT__INDEX;
    public static final Index COMMENT__OWNER_ID__INDEX = Indexes0.COMMENT__OWNER_ID__INDEX;
    public static final Index DIARY__INDEX = Indexes0.DIARY__INDEX;
    public static final Index DIARY__OWNER_ID__INDEX = Indexes0.DIARY__OWNER_ID__INDEX;
    public static final Index MESSAGE__OWNER_ID__INDEX = Indexes0.MESSAGE__OWNER_ID__INDEX;
    public static final Index STATISTICS__INDEX = Indexes0.STATISTICS__INDEX;
    public static final Index STATISTICS__OWNER_ID__INDEX = Indexes0.STATISTICS__OWNER_ID__INDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ANIMATION_STAFF_RELATION__INDEX = Internal.createIndex("animation_staff_relation__index", AnimationStaffRelation.ANIMATION_STAFF_RELATION, new OrderField[] { AnimationStaffRelation.ANIMATION_STAFF_RELATION.ANIMATION_ID, AnimationStaffRelation.ANIMATION_STAFF_RELATION.STAFF_ID, AnimationStaffRelation.ANIMATION_STAFF_RELATION.STAFF_TYPE }, true);
        public static Index ANIMATION_TAG_RELATION__INDEX = Internal.createIndex("animation_tag_relation__index", AnimationTagRelation.ANIMATION_TAG_RELATION, new OrderField[] { AnimationTagRelation.ANIMATION_TAG_RELATION.ANIMATION_ID, AnimationTagRelation.ANIMATION_TAG_RELATION.TAG_ID }, true);
        public static Index COMMENT__INDEX = Internal.createIndex("comment__index", Comment.COMMENT, new OrderField[] { Comment.COMMENT.OWNER_ID, Comment.COMMENT.ANIMATION_ID }, true);
        public static Index COMMENT__OWNER_ID__INDEX = Internal.createIndex("comment__owner_id__index", Comment.COMMENT, new OrderField[] { Comment.COMMENT.OWNER_ID }, false);
        public static Index DIARY__INDEX = Internal.createIndex("diary__index", Diary.DIARY, new OrderField[] { Diary.DIARY.OWNER_ID, Diary.DIARY.ANIMATION_ID }, true);
        public static Index DIARY__OWNER_ID__INDEX = Internal.createIndex("diary__owner_id__index", Diary.DIARY, new OrderField[] { Diary.DIARY.OWNER_ID }, false);
        public static Index MESSAGE__OWNER_ID__INDEX = Internal.createIndex("message__owner_id__index", Message.MESSAGE, new OrderField[] { Message.MESSAGE.OWNER_ID }, false);
        public static Index STATISTICS__INDEX = Internal.createIndex("statistics__index", Statistics.STATISTICS, new OrderField[] { Statistics.STATISTICS.OWNER_ID, Statistics.STATISTICS.TYPE, Statistics.STATISTICS.KEY }, true);
        public static Index STATISTICS__OWNER_ID__INDEX = Internal.createIndex("statistics__owner_id__index", Statistics.STATISTICS, new OrderField[] { Statistics.STATISTICS.OWNER_ID }, false);
    }
}
