/*
 * This file is generated by jOOQ.
 */
package com.heerkirov.animation.jooq;


import com.heerkirov.animation.jooq.tables.Animation;
import com.heerkirov.animation.jooq.tables.AnimationStaffRelation;
import com.heerkirov.animation.jooq.tables.AnimationTagRelation;
import com.heerkirov.animation.jooq.tables.Comment;
import com.heerkirov.animation.jooq.tables.Diary;
import com.heerkirov.animation.jooq.tables.Message;
import com.heerkirov.animation.jooq.tables.Staff;
import com.heerkirov.animation.jooq.tables.Statistics;
import com.heerkirov.animation.jooq.tables.Tag;
import com.heerkirov.animation.jooq.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1156137530;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.animation</code>.
     */
    public final Animation ANIMATION = Animation.ANIMATION;

    /**
     * The table <code>public.animation_staff_relation</code>.
     */
    public final AnimationStaffRelation ANIMATION_STAFF_RELATION = AnimationStaffRelation.ANIMATION_STAFF_RELATION;

    /**
     * The table <code>public.animation_tag_relation</code>.
     */
    public final AnimationTagRelation ANIMATION_TAG_RELATION = AnimationTagRelation.ANIMATION_TAG_RELATION;

    /**
     * The table <code>public.comment</code>.
     */
    public final Comment COMMENT = Comment.COMMENT;

    /**
     * The table <code>public.diary</code>.
     */
    public final Diary DIARY = Diary.DIARY;

    /**
     * The table <code>public.message</code>.
     */
    public final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>public.staff</code>.
     */
    public final Staff STAFF = Staff.STAFF;

    /**
     * The table <code>public.statistics</code>.
     */
    public final Statistics STATISTICS = Statistics.STATISTICS;

    /**
     * The table <code>public.tag</code>.
     */
    public final Tag TAG = Tag.TAG;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Animation.ANIMATION,
            AnimationStaffRelation.ANIMATION_STAFF_RELATION,
            AnimationTagRelation.ANIMATION_TAG_RELATION,
            Comment.COMMENT,
            Diary.DIARY,
            Message.MESSAGE,
            Staff.STAFF,
            Statistics.STATISTICS,
            Tag.TAG,
            User.USER);
    }
}
