/*
 * This file is generated by jOOQ.
 */
package com.heerkirov.animation.jooq;


import com.heerkirov.animation.jooq.tables.Animation;
import com.heerkirov.animation.jooq.tables.AnimationStaffRelation;
import com.heerkirov.animation.jooq.tables.AnimationTagRelation;
import com.heerkirov.animation.jooq.tables.Comment;
import com.heerkirov.animation.jooq.tables.Diary;
import com.heerkirov.animation.jooq.tables.Message;
import com.heerkirov.animation.jooq.tables.Staff;
import com.heerkirov.animation.jooq.tables.Statistics;
import com.heerkirov.animation.jooq.tables.Tag;
import com.heerkirov.animation.jooq.tables.User;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.animation</code>.
     */
    public static final Animation ANIMATION = Animation.ANIMATION;

    /**
     * The table <code>public.animation_staff_relation</code>.
     */
    public static final AnimationStaffRelation ANIMATION_STAFF_RELATION = AnimationStaffRelation.ANIMATION_STAFF_RELATION;

    /**
     * The table <code>public.animation_tag_relation</code>.
     */
    public static final AnimationTagRelation ANIMATION_TAG_RELATION = AnimationTagRelation.ANIMATION_TAG_RELATION;

    /**
     * The table <code>public.comment</code>.
     */
    public static final Comment COMMENT = Comment.COMMENT;

    /**
     * The table <code>public.diary</code>.
     */
    public static final Diary DIARY = Diary.DIARY;

    /**
     * The table <code>public.message</code>.
     */
    public static final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>public.staff</code>.
     */
    public static final Staff STAFF = Staff.STAFF;

    /**
     * The table <code>public.statistics</code>.
     */
    public static final Statistics STATISTICS = Statistics.STATISTICS;

    /**
     * The table <code>public.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;
}
