ALTER TABLE tag
    ADD COLUMN animation_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN "group" VARCHAR(16) DEFAULT NULL,
    ADD COLUMN ordinal INTEGER NOT NULL DEFAULT 0;

ALTER TABLE staff
    ADD COLUMN animation_count INTEGER NOT NULL DEFAULT 0;